replicaCount: 3

image:
  repository: ghcr.io/maryamjabrailova04/agrivo-backend
  tag: "9a6d2006ab9383cd5a0d4bc5ea7ca22deee58698"
  pullPolicy: IfNotPresent

config:
  nodeEnv: production
  port: "5000"
  jwtExpiresIn: 7d
  frontendUrl: https://agrivo.site

secret:
  databaseUrl: replace-with-key-vault-csi
  jwtSecret: replace-with-key-vault-csi

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65
keyVault:
  enabled: true
  name: kv-agrivo-prod-4fe19b
  tenantId: "cdfc3bf8-f209-418a-8563-7f864d83f183"
  clientId: "6a05b61c-d40d-40f9-af0b-ba4dafc32c79"
  usePodIdentity: "false"
  useVMManagedIdentity: "true"
  secrets:
    - objectName: DATABASE-URL
      objectType: secret
      envName: DATABASE_URL
    - objectName: JWT-SECRET
      objectType: secret
      envName: JWT_SECRET
monitoring:
  enabled: true
  interval: 15s
  scrapeTimeout: 10s
  labels:
    release: kube-prometheus-stack
  alerts:
    enabled: true
  
