apiVersion: v1
kind: ConfigMap
metadata:
  name: agrivo-backend-config
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.config.port | quote }}
  JWT_EXPIRES_IN: {{ .Values.config.jwtExpiresIn | quote }}
  FRONTEND_URL: {{ .Values.config.frontendUrl | quote }}
