{{- if not .Values.keyVault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: agrivo-backend-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
{{- end }}
