apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrivo-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: agrivo-frontend
  template:
    metadata:
      labels:
        app: agrivo-frontend
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
{{ toYaml .Values.containerSecurityContext | indent 12 }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
{{ toYaml .Values.resources | indent 12 }}
