apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.dev }}
  labels:
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurity.enforce }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurity.audit }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurity.warn }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.prod }}
  labels:
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurity.enforce }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurity.audit }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurity.warn }}
