certManager:
  enabled: true
  email: admin@example.com

clusterIssuers:
  staging:
    name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
  production:
    name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
