apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agrivo-ingress-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/MaryamJabrailova04/Agrivo.git
    targetRevision: main
    path: k8s/helm/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
