replicaCount: 1

image:
  repository: harbor.example.com/agrivo/frontend
  tag: "5dea01290b0789d257b593eef697c92f569db1b2"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: dev.agrivo.example.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  tls:
    enabled: true
    secretName: agrivo-frontend-dev-tls
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
