replicaCount: 1

image:
  repository: ghcr.io/maryamjabrailova04/agrivo-frontend
  tag: "00b77bb554efca00b7b3a53329236764530a14fe"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: dev.agrivo.example.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  tls:
    enabled: true
    secretName: agrivo-frontend-dev-tls
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
