replicaCount: 3

image:
  repository: harbor.example.com/agrivo/frontend
  tag: CHANGE_ME_IMMUTABLE_GIT_SHA
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: agrivo.example.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
  tls:
    enabled: true
    secretName: agrivo-frontend-prod-tls
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
