apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agrivo-ingress-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/MaryamJabrailova04/Agrivo.git
    targetRevision: main
    path: k8s/helm/ingress
    helm:
      valueFiles:
        - values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
