- name: Install kube-score
  run: |
    VERSION=1.20.0

    curl -L \
      -o kube-score.tar.gz \
      https://github.com/zegl/kube-score/releases/download/v${VERSION}/kube-score_${VERSION}_linux_amd64.tar.gz

    tar -xzf kube-score.tar.gz
    chmod +x kube-score
    sudo mv kube-score /usr/local/bin/

    kube-score version
