replicaCount: 2
imagePullSecrets: []
image:
  repository: ghcr.io/maryamjabrailova04/agrivo-frontend
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: agrivo.example.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  tls:
    enabled: true
    secretName: agrivo-frontend-tls
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
serviceAccount:
  create: true
  name: agrivo-frontend
  automountServiceAccountToken: false

rbac:
  create: true

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  fsGroup: 101
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

networkPolicy:
  enabled: true
  ingress:
    allowFromIngressController: true
  egress:
    allowBackend: true
    backendAppLabel: agrivo-backend
